### ISSUE TITLE
No friends are appearing in invite friends page

### ISSUE THREAD

**Issue by David-N-Lopez** [David-N-Lopez/CaptionIt#2]

**Comment by veeranjain04** [comment]
Hi Nicolas,
Please check attached screen shot for same. Working fine on Android as well on iOS
FYI :- Make sure your facebook friends use CaptionIt application and linked application with facebook.

Thanks
![whatsapp image 2018-07-14 at 10 39 18 am](https://user-images.githubusercontent.com/17514235/42721121-42d555ba-8752-11e8-95c9-f47ffa7de075.jpeg)

**Comment by Nicorules** [comment]
I had several problems trying to connect to my facebook friends that had the game. Maybe things are working better rn. I will test this again.
